name: Database Schema Updates to Supabase

on:
  push:
    branches: [ main, develop ]
    paths: [ 'database/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'database/**' ]

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
        
    - name: Link to Supabase project
      run: |
        cd database
        supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
    - name: Run database migrations
      run: |
        cd database
        supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
    - name: Generate TypeScript types
      run: |
        cd database
        supabase gen types typescript --local > types/supabase.ts
      continue-on-error: true
      
    - name: Validate schema
      run: |
        cd database
        supabase db diff --schema public
      continue-on-error: true
