name: Integration Testing & Cross-Service Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../backend && npm ci
        
    - name: Build all services
      run: |
        cd frontend && npm run build
        cd ../backend && npm run build
      env:
        NODE_ENV: production
        
    - name: Start services for testing
      run: |
        cd backend && npm start &
        sleep 10
        cd ../frontend && npm start &
        sleep 15
      env:
        NODE_ENV: test
        
    - name: Run integration tests
      run: |
        npm run test:integration
      env:
        VERCEL_FRONTEND_URL: ${{ secrets.VERCEL_FRONTEND_URL }}
        RAILWAY_BACKEND_URL: ${{ secrets.RAILWAY_BACKEND_URL }}
        SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
      continue-on-error: true
      
    - name: Test API endpoints
      run: |
        curl -f ${{ secrets.RAILWAY_BACKEND_URL }}/api/health
        curl -f ${{ secrets.RAILWAY_BACKEND_URL }}/api/users
      continue-on-error: true
      
    - name: Test frontend-backend communication
      run: |
        curl -f ${{ secrets.VERCEL_FRONTEND_URL }}
      continue-on-error: true
      
    - name: Security scan
      uses: securecodewarrior/github-action-add-sarif@v1
      with:
        sarif-file: security-scan-results.sarif
      continue-on-error: true
